Remove factory dependency in production
Instead, access faker directly.

The update-requirements script also gets a nice status check in the beginning

diff --git a/bin/update-requirements b/bin/update-requirements
--- a/bin/update-requirements
+++ b/bin/update-requirements
@@ -1,2 +1,7 @@
 #!/bin/bash
+if ! poetry check
+then
+    echo "Poetry check failed. Please fix any issues before using this tool"
+    exit 1
+fi
 poetry export --format requirements.txt --output requirements.txt
